### ISSUE TITLE
Bug in "base_pipeline.py"

### ISSUE THREAD

**Issue by malema-ramonyai** [MichelleLochner/astronomaly#12]
There is a problem with line **282** in `base_pipeline.py`. I solved the problem by replacing `np.isnan`  with `pd.isnull`
![image](https://user-images.githubusercontent.com/69205901/112689684-4d14c980-8e83-11eb-93fc-e7667ecc233b.png)

**Comment by MichelleLochner** [comment]
Should be fixed in upcoming PR #14
