### ISSUE TITLE
Bug in "logging_tools.py"

### ISSUE THREAD

**Issue by malema-ramonyai** [MichelleLochner/astronomaly#13]
There is logging error coming from lines **183-192** in `logging_tools.py`. I temporarily solved the problem by commenting out lines **183-192** in `logging_tools.py`.

![image](https://user-images.githubusercontent.com/69205901/112689389-e0013400-8e82-11eb-9eaf-43fe54f24d5f.png)

**Comment by MichelleLochner** [comment]
Fixed in https://github.com/MichelleLochner/astronomaly/commit/58cb06d9e3fc3d286bae7888a8bbbb291e55db97#diff-d9003f68034c6c48d2f469328d4415de0b554316ab6018a1a62d62ac1cf1624e
